### ISSUE TITLE
Mouseover a markdown cell changes its format

### ISSUE THREAD

**Issue by papajohn** [dsten/notebook#1]
When I hover over a markdown cell in *simple mode*, it changes background color from white to gray as if being edited. 

![markdown](https://cloud.githubusercontent.com/assets/320145/9362431/2fcfd436-4655-11e5-9ad5-e142fef99246.gif)

**Comment by papajohn** [comment]
Nevermind — I see that's how it's designed. I think I'll change it a bit, though.

**Comment by papajohn** [comment]
Ok, I poked around. I think the behavior I really want is to just freeze all the markdown cells & have students only edit the code cells. Does that seem feasible @alvinwan

**Comment by alvinwan** [comment]
Of course. I'll do that.
